[project]
name = "zotero-web"
version = "0.2.0"
description = "A web interface for Zotero"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiofiles>=24.1.0",
    "aiohttp>=3.12.15",
    "aiohttp-jinja2>=1.6",
    "flask>=3.1.1",
    "psutil>=7.0.0",
    "watchdog>=6.0.0",
]
